# Numpy
    

    - Numpy means Numerical Python.
    - Its Fastest.
    - Its backend is written in c Language.
    - It performs Vectorised Operations. the
    - It uses Contigous Memory

In [2]:
import numpy as np

In [5]:
# Creating an array (list) using numpy
arr1 = np.array([0,1,2,3])

In [6]:
arr1.size

4

In [8]:
arr1.shape

(4,)

# Dimenstions

    - One Dimention = Vector
    - Two Dimention = Matrix
    - Three Dimention = Cube
    - n Dimention = ...

In [12]:
arr1.ndim

1

In [14]:
# numpy range funciton returns array not like
# python range function that returns an object which you have to typecast to have list.

arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Two Dimention Array

# two dimentions arrays are the arrays with x and y
arr2d = np.array([[1,2,3], [11,22,33], [111,222,333], [1111,2222,3333]])
arr2d

array([[   1,    2,    3],
       [  11,   22,   33],
       [ 111,  222,  333],
       [1111, 2222, 3333]])

In [19]:
arr2d.shape

(4, 3)

In [54]:
# arr2d = np.arange(20).reshape(1,20)
# arr2d = np.arange(20).reshape(20,1)
arr2d = np.arange(20).reshape(4, 5)
# arr2d = np.arange(20).reshape(10,2)
# arr2d = np.arange(20).reshape(2,10)

arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
# Scaler
arr = np.array(10)
arr

array(10)

In [34]:
arr.ndim

0

In [35]:
# Vector 
arr = np.array([10])
arr

array([10])

In [36]:
arr.ndim

1

In [50]:
# Three Dimentions

arr3d = np.arange(64).reshape(4,4,4)# (depth, row, colums) or (matrixnum, row, col)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [55]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [56]:
arr2d[3][2]

17

In [58]:
arr1

array([0, 1, 2, 3])

In [60]:
newArr1 = []
for n in arr1:
   newArr1.append(n*2)

newArr1

[0, 2, 4, 6]

In [61]:
[n**2 for n in arr1]

[0, 1, 4, 9]

In [62]:
arr1 * 2

array([0, 2, 4, 6])

In [63]:
arr1 / 2

array([0. , 0.5, 1. , 1.5])

In [64]:
arr1 * 2

array([0, 2, 4, 6])

In [66]:
arr1*3

array([0, 3, 6, 9])

In [68]:
arr3d * 2

array([[[  0,   2,   4,   6],
        [  8,  10,  12,  14],
        [ 16,  18,  20,  22],
        [ 24,  26,  28,  30]],

       [[ 32,  34,  36,  38],
        [ 40,  42,  44,  46],
        [ 48,  50,  52,  54],
        [ 56,  58,  60,  62]],

       [[ 64,  66,  68,  70],
        [ 72,  74,  76,  78],
        [ 80,  82,  84,  86],
        [ 88,  90,  92,  94]],

       [[ 96,  98, 100, 102],
        [104, 106, 108, 110],
        [112, 114, 116, 118],
        [120, 122, 124, 126]]])

In [77]:
# mirroring = elementwise operation
a = np.arange(25).reshape(5,5)
b = np.arange(25, 50).reshape(5,5)

print(a, b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] [[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [80]:
# a @ b
a.dot(b)

array([[ 400,  410,  420,  430,  440],
       [1275, 1310, 1345, 1380, 1415],
       [2150, 2210, 2270, 2330, 2390],
       [3025, 3110, 3195, 3280, 3365],
       [3900, 4010, 4120, 4230, 4340]])

In [81]:
c = np.arange(20).reshape(5,4)

In [82]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [84]:
# (5,5) and (5,4)
b@c
# use @ for liner algebra multification

array([[1120, 1255, 1390, 1525],
       [1320, 1480, 1640, 1800],
       [1520, 1705, 1890, 2075],
       [1720, 1930, 2140, 2350],
       [1920, 2155, 2390, 2625]])

# Array Slicing

In [85]:
a 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [86]:
type(a[2,3])

numpy.int32

In [87]:
#  array [row, col] or [start:end, start:end]

a[2:3, 3:4]

array([[13]])

In [88]:
a[1:4, 3]

array([ 8, 13, 18])

In [90]:
a[1:4, 3:4]

array([[ 8],
       [13],
       [18]])

# Querrying Array

In [95]:
mask = a > 5 # Mask

mask

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [99]:
a[mask]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [100]:
a[a > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [101]:
a[a > 7 ] = 100

In [102]:
a

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [104]:
np.where(a > 10, 0, a)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [106]:
a[(a%2==0) & (a%7==0)]

array([0])

In [107]:
a[(a%2==0) | (a%7==0)]

array([  0,   2,   4,   6,   7, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100])

In [108]:
np.where((a%2==0) | (a%7==0), 'Wow', 'OH')

array([['Wow', 'OH', 'Wow', 'OH', 'Wow'],
       ['OH', 'Wow', 'Wow', 'Wow', 'Wow'],
       ['Wow', 'Wow', 'Wow', 'Wow', 'Wow'],
       ['Wow', 'Wow', 'Wow', 'Wow', 'Wow'],
       ['Wow', 'Wow', 'Wow', 'Wow', 'Wow']], dtype='<U3')