# Numpy (Sir Nasir)
    

    * Numpy means Numerical Python.
    * Its Fastest.
    * Its backend is written in c Language.
    * It performs Vectorised Operations. the
    * It uses Contigous Memory

In [2]:
import numpy as np

In [5]:
# Creating an array (list) using numpy
arr1 = np.array([0,1,2,3])

In [6]:
arr1.size

4

In [8]:
arr1.shape

(4,)

# Dimenstions

    - One Dimention = Vector
    - Two Dimention = Matrix
    - Three Dimention = Cube
    - n Dimention = ...

In [12]:
arr1.ndim

1

In [14]:
# numpy range funciton returns array not like
# python range function that returns an object which you have to typecast to have list.

arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Two Dimention Array

# two dimentions arrays are the arrays with x and y
arr2d = np.array([[1,2,3], [11,22,33], [111,222,333], [1111,2222,3333]])
arr2d

array([[   1,    2,    3],
       [  11,   22,   33],
       [ 111,  222,  333],
       [1111, 2222, 3333]])

In [19]:
arr2d.shape

(4, 3)

In [54]:
# arr2d = np.arange(20).reshape(1,20)
# arr2d = np.arange(20).reshape(20,1)
arr2d = np.arange(20).reshape(4, 5)
# arr2d = np.arange(20).reshape(10,2)
# arr2d = np.arange(20).reshape(2,10)

arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
# Scaler
arr = np.array(10)
arr

array(10)

In [34]:
arr.ndim

0

In [35]:
# Vector 
arr = np.array([10])
arr

array([10])

In [36]:
arr.ndim

1

In [50]:
# Three Dimentions

arr3d = np.arange(64).reshape(4,4,4)# (depth, row, colums) or (matrixnum, row, col)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [55]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [56]:
arr2d[3][2]

17

In [58]:
arr1

array([0, 1, 2, 3])

In [60]:
newArr1 = []
for n in arr1:
   newArr1.append(n*2)

newArr1

[0, 2, 4, 6]

In [61]:
[n**2 for n in arr1]

[0, 1, 4, 9]

In [62]:
arr1 * 2

array([0, 2, 4, 6])

In [63]:
arr1 / 2

array([0. , 0.5, 1. , 1.5])

In [64]:
arr1 * 2

array([0, 2, 4, 6])

In [66]:
arr1*3

array([0, 3, 6, 9])

In [68]:
arr3d * 2

array([[[  0,   2,   4,   6],
        [  8,  10,  12,  14],
        [ 16,  18,  20,  22],
        [ 24,  26,  28,  30]],

       [[ 32,  34,  36,  38],
        [ 40,  42,  44,  46],
        [ 48,  50,  52,  54],
        [ 56,  58,  60,  62]],

       [[ 64,  66,  68,  70],
        [ 72,  74,  76,  78],
        [ 80,  82,  84,  86],
        [ 88,  90,  92,  94]],

       [[ 96,  98, 100, 102],
        [104, 106, 108, 110],
        [112, 114, 116, 118],
        [120, 122, 124, 126]]])

In [77]:
# mirroring = elementwise operation
a = np.arange(25).reshape(5,5)
b = np.arange(25, 50).reshape(5,5)

print(a, b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] [[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [80]:
# a @ b
a.dot(b)

array([[ 400,  410,  420,  430,  440],
       [1275, 1310, 1345, 1380, 1415],
       [2150, 2210, 2270, 2330, 2390],
       [3025, 3110, 3195, 3280, 3365],
       [3900, 4010, 4120, 4230, 4340]])

In [81]:
c = np.arange(20).reshape(5,4)

In [82]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [84]:
# (5,5) and (5,4)
b@c
# use @ for liner algebra multification

array([[1120, 1255, 1390, 1525],
       [1320, 1480, 1640, 1800],
       [1520, 1705, 1890, 2075],
       [1720, 1930, 2140, 2350],
       [1920, 2155, 2390, 2625]])

# Array Slicing

In [85]:
a 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [86]:
type(a[2,3])

numpy.int32

In [87]:
#  array [row, col] or [start:end, start:end]

a[2:3, 3:4]

array([[13]])

In [88]:
a[1:4, 3]

array([ 8, 13, 18])

In [90]:
a[1:4, 3:4]

array([[ 8],
       [13],
       [18]])

# Querrying Array

In [95]:
mask = a > 5 # Mask

mask

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [99]:
a[mask]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [100]:
a[a > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [101]:
a[a > 7 ] = 100

In [102]:
a

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [104]:
np.where(a > 10, 0, a)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [106]:
a[(a%2==0) & (a%7==0)]

array([0])

In [107]:
a[(a%2==0) | (a%7==0)]

array([  0,   2,   4,   6,   7, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100])

In [108]:
np.where((a%2==0) | (a%7==0), 'Wow', 'OH')

array([['Wow', 'OH', 'Wow', 'OH', 'Wow'],
       ['OH', 'Wow', 'Wow', 'Wow', 'Wow'],
       ['Wow', 'Wow', 'Wow', 'Wow', 'Wow'],
       ['Wow', 'Wow', 'Wow', 'Wow', 'Wow'],
       ['Wow', 'Wow', 'Wow', 'Wow', 'Wow']], dtype='<U3')

### Sir Nasir Class End

In [8]:
# need 10 rows and 10 cols
a = np.arange(100).reshape(10,10)
# a.shape # number of axis in dimension
a.ndim # number of dimension 

2

In [15]:
np.arange(27)
# output array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
#        17, 18, 19, 20, 21, 22, 23, 24, 25, 26])
np.arange(27).reshape(3,3,3)
# output array([[[ 0,  1,  2],
#         [ 3,  4,  5],
#         [ 6,  7,  8]],

#        [[ 9, 10, 11],
#         [12, 13, 14],
#         [15, 16, 17]],

#        [[18, 19, 20],
#         [21, 22, 23],
#         [24, 25, 26]]])

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
# if we have 4 images what would be the resolation 8X8 

np.arange(4*8*8).reshape(4, 8, 8)

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62,  63]],

       [[ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127]],

       [[128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [17]:
np.random.randint(0,255, 100)

array([ 85, 248,  64, 235,   9, 235,  13,  37, 232,  55, 129, 140,  67,
       147, 162,  94,  83, 143, 161, 172, 144,  51, 209, 157, 105, 204,
        45,  67,  18,  78,  19, 133, 254, 196, 109, 146,  34, 160, 224,
       203, 155, 221,  17,  10, 250, 122, 162, 142, 154, 235,  67, 136,
       207, 117,  63,  57,  41, 246, 121, 196, 127, 240, 114, 238,   3,
       149, 167,  71,  52,  62, 240, 112, 227, 123, 189,  84, 219, 158,
        86, 232, 215, 146, 207, 110,  46, 199, 119, 216,  61, 221,  49,
       252, 234,  87, 176, 185, 114,  24,  82, 111])

In [18]:
a = np.array([[1,2,3], [4,5,6]])

a[:, -2:]

array([[2, 3],
       [5, 6]])

In [19]:
# if we convert video to numpy data it will be 5 dimension data

In [25]:
display(np.zeros(10))
display(np.ones(10))
display(np.empty(10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
# linspace function genrates linerspace/steps between a range

np.linspace(1, 2, 5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [29]:
np.linspace(1, 60, 3)

array([ 1. , 30.5, 60. ])

In [41]:
a = np.arange(27).reshape(3,3,3)

a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [42]:
# ones like function temporarly changes array elemets to 1
np.ones_like(a)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [46]:
# sort function sort array elemets

np.sort(a)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [59]:
np.arange(50*3*3).reshape(-1,3,3) # -1 in reshape means it will handle calculation by it self
# can be used in any parameter and can only use in one parameter at a time

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8]],

       [[  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17]],

       [[ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26]],

       [[ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35]],

       [[ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53]],

       [[ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62]],

       [[ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71]],

       [[ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80]],

       [[ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98]],

       [[ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107]],

       [[108, 109, 110],
        [111, 112, 113],
        [114, 115, 116]],


In [63]:
# when ever you see arg in numpy it means index

a = np.array([1,8 , 4,30, 5 , 5])
print(np.argmax(a))
print(np.argmin(a))
print(np.argsort(a))

3
0
[0 2 4 5 1 3]


In [65]:
labels = ['cat', 'dogs', 'apple', 'orange']
prediction = [20, 50, 40, 15]
index = np.argmax(prediction)

print(labels[index])

dogs


# Concatination

In [66]:
a = np.arange(1,11).reshape(5,2)
b = np.arange(11,21).reshape(5,2)
display(a)
display(b)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [70]:
np.concatenate((a, b)) # default axis 0

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [71]:
np.concatenate((a,b ), axis=1)

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [72]:
np.stack((a,b))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [73]:
np.stack((a,b), axis=1)

array([[[ 1,  2],
        [11, 12]],

       [[ 3,  4],
        [13, 14]],

       [[ 5,  6],
        [15, 16]],

       [[ 7,  8],
        [17, 18]],

       [[ 9, 10],
        [19, 20]]])

In [75]:
np.hstack(((a,b)))

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [77]:
np.vstack(((a,b)))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [79]:
a.sum()

55

In [81]:
a = np.array([[1,2,3], [3,4,5]])

In [85]:
a.sum(axis=1)

array([ 6, 12])

## Slicing, Indexing, Fancy Slicing, Boolean Slicing

In [86]:
a = np.arange(4*4).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [87]:
a[0]

array([0, 1, 2, 3])

In [88]:
a[2]

array([ 8,  9, 10, 11])

In [89]:
a[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [91]:
display(a)
display(a[[1,2,0,1]]) # this is fancy slicing where we specify what indexs we want

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [93]:
a % 2 == 0

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [95]:
b = np.arange(1,7)
b[b % 2 == 0]

array([2, 4, 6])

In [97]:
np.split(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [98]:
np.split(a,2, axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [99]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [100]:
np.hsplit(a, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]